const getters = {
    sidebar: state => state.app.sidebar,
    size: state => state.app.size,
    device: state => state.app.device,
    curMenu: state => state.app.curMenu,
    visitedViews: state => state.tagsView.visitedViews,
    cachedViews: state => state.tagsView.cachedViews,
    token: state => state.user.token,
    avatar: state => state.user.avatar,
    name: state => state.user.name,
    introduction: state => state.user.introduction,
    roles: state => state.user.roles,
    permissions: state => state.user.permissions,
    permission_routes: state => state.permission.routes,
    userId: state => state.user.id,
    appId: state => state.user.appId,
    appList: state => state.user.appList,
    myApps: state => state.user.myApps,
    branchId: state => state.user.branchId,
    windSize: state => state.app.windSize,
    tableHeight: state => state.app.windSize.tableHeight,
    roleCodes: state => state.user.roleCodes,
}
export default getters